/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { WagerCoin__factory } from "./WagerCoin__factory";
export { WagerMultiWallet__factory } from "./WagerMultiWallet__factory";
