/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWagerTicketRenderer__factory } from "./IWagerTicketRenderer__factory";
export { WagerCoin__factory } from "./WagerCoin__factory";
export { WagerMultiWallet__factory } from "./WagerMultiWallet__factory";
export { WagerTicket__factory } from "./WagerTicket__factory";
