/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IWagerTicketRenderer } from "./IWagerTicketRenderer";
export type { WagerCoin } from "./WagerCoin";
export type { WagerMultiWallet } from "./WagerMultiWallet";
export type { WagerTicket } from "./WagerTicket";
